export class Meal {
    constructor(
        public idMeal?: string | undefined,
        public strMeal?: string,
        public strMealThumb?: string,
        public strCategory?: string,
        public strTags?: string,
        public strInstructions?: string,
        public meals?: Meal,
        public strArea?: string |null,
        public strYoutube?:  string,
        public strDrinkAlternate?: string | undefined | null,
        public strIngredient1?:  string,
        public strIngredient2?:  string,
        public strIngredient3?:  string,
        public strIngredient4?:  string,
        public strIngredient5?:  string,
        public strIngredient6?:  string,
        public strIngredient7?:  string,
        public strIngredient8?:  string,
        public strIngredient9?:  string,
        public strIngredient10?:  string,
        public strIngredient11?:  string,
        public strIngredient12?:  string,
        public strIngredient13?: string | null,
        public strIngredient14?: string | null,
        public strIngredient15?: string | null,
        public strIngredient16?: string | null,
        public strIngredient17?: string | null,
        public strIngredient18?: string | null,
        public strIngredient19?: string | null,
        public strIngredient20?: string | null,
        public strMeasure1?: string | null,
        public strMeasure2?: string | null,
        public strMeasure3?: string | null,
        public strMeasure4?: string | null,
        public strMeasure5?: string | null,
        public strMeasure6?: string | null,
        public strMeasure7?: string | null,
        public strMeasure8?: string | null,
        public strMeasure9?: string | null,
        public strMeasure10?: string | null,
        public strMeasure11?: string | null,
        public strMeasure12?: string | null,
        public strMeasure13?: string | null,
        public strMeasure14?: string | null,
        public strMeasure15?: string | null,
        public strMeasure16?: string | null,
        public strMeasure17?: string | null,
        public strMeasure18?: string | null,
        public strMeasure19?: string | null,
        public strMeasure20?: string | null,
        public strSource?: string | null,
        public strImageSource?: string | null,
        public strCreativeCommonsConfirmed?: string | null,
        public dateModified?: string | null | null
    ) {}
}